### Working with Missing Data in Pandas
In Pandas, missing data occurs when some values are missing or not collected properly and these missing values are represented as:
- None: A Python object used to represent missing values in object-type arrays.
- NaN: A special floating-point value from NumPy which is recognized by all systems that use IEEE floating-point standards.

#### 1. Using `isnull()`
`isnull()` returns a DataFrame of Boolean value where True represents missing data (NaN). This is simple if we want to find and fill missing data in a dataset.

In [26]:
import numpy as np
import pandas as pd

df = pd.read_csv("employees.csv")
bool_series = pd.isnull(df["Gender"])
df_cleaned = df[bool_series]

print(df_cleaned)

    First Name Gender  Start Date Last Login Time  Salary  Bonus %  \
20        Lois    NaN   4/22/1995         7:18 PM   64714    4.934
22      Joshua    NaN    3/8/2012         1:58 AM   90816   18.816
27       Scott    NaN   7/11/1991         6:58 PM  122367    5.218
31       Joyce    NaN   2/20/2005         2:40 PM   88657   12.752
41   Christine    NaN   6/28/2015         1:08 AM   66582   11.308
..         ...    ...         ...             ...     ...      ...
961    Antonio    NaN   6/18/1989         9:37 PM  103050    3.050
972     Victor    NaN   7/28/2006         2:49 PM   76381   11.159
985    Stephen    NaN   7/10/1983         8:10 PM   85668    1.909
989     Justin    NaN   2/10/1991         4:58 PM   38344    3.794
995      Henry    NaN  11/23/2014         6:09 AM  132483   16.655

    Senior Management                  Team
20               True                 Legal
22               True       Client Services
27              False                 Legal
31              False               Product
41               True  Business Development
..                ...                   ...
961             False                 Legal
972              True                 Sales
985             False                 Legal
989             False                 Legal
995             False          Distribution

[145 rows x 8 columns]

In [15]:
df.isnull().sum()

First Name            67
Gender               145
Start Date             0
Last Login Time        0
Salary                 0
Bonus %                0
Senior Management     67
Team                  43
dtype: int64

In [14]:
df["Gender"].isnull().sum()

np.int64(145)

#### 2. Using `isnull()`
`isnull()` returns a DataFrame of Boolean values where True indices missing data (NaN).

It is used to detect missing values just like `isnull()`.

In [27]:
data = {'Name': ['Ali', 'Zoya', np.nan, 'Muzzamil'],
        'Age': [25, np.nan, 22, 28]}

df = pd.DataFrame(data)

print(df.isna())

    Name    Age
0  False  False
1  False   True
2   True  False
3  False  False

#### 3. Using `notnull()`
`notnull()` function returns a DataFrame with Boolean values where True indicates non-missing (valid) data.

In [19]:
data = {'Name': ['Ali', 'Zoya', np.nan, 'Muzzamil'],
        'Age': [25, np.nan, 22, 28]}

df = pd.DataFrame(data)

print(df.notnull())

    Name    Age
0   True   True
1   True  False
2  False   True
3   True   True

### Filling Missing Values in Pandas
Following functions allow us to replace missing values with a specified value or use interpolation methods to find the missing data.

#### 1. Using `fillna()`
`fillna()` used to replace missing values (NaN) with a given value. Lets see various example for this.

In [28]:
d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)

df.fillna(0)

   First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

In [24]:
df = pd.read_csv("employees.csv")
df['Gender'].fillna("Unknown")

0         Male
1         Male
2       Female
3         Male
4         Male
        ...
995    Unknown
996       Male
997       Male
998       Male
999       Male
Name: Gender, Length: 1000, dtype: str

### Dropping Missing Values in Pandas
The `dropna()` function used to removes rows or columns with NaN values. It can be used to drop data based on different conditions.

#### 1. Dropping Rows with At Least One Null Value
Remove rows that contain at least one missing value.

In [25]:
dict = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score': [52, 40, 80, 98],
        'Fourth Score': [np.nan, np.nan, np.nan, 65]}
df = pd.DataFrame(dict)

df.dropna()

   First Score  Second Score  Third Score  Fourth Score
3         95.0          56.0           98          65.0

#### 2. Dropping Rows with All Null Values
We can drop rows where all values are missing using `dropna(how='all')`.

In [29]:
dict = {'First Score': [100, np.nan, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score': [52, np.nan, 80, 98],
        'Fourth Score': [np.nan, np.nan, np.nan, 65]}
df = pd.DataFrame(dict)

df.dropna(how='all')

   First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0         52.0           NaN
2          NaN          45.0         80.0           NaN
3         95.0          56.0         98.0          65.0

#### 3. Dropping Columns with At Least One Null Value
To remove columns that contain at least one missing value we use `dropna(axis=1)`.

In [30]:
dict = {'First Score': [100, np.nan, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score': [52, np.nan, 80, 98],
        'Fourth Score': [60, 67, 68, 65]}
df = pd.DataFrame(dict)

df.dropna(axis=1)

   Fourth Score
0            60
1            67
2            68
3            65